version: 2.1
workflows:
  default_workflow:
    jobs:
      - lint
      - deploy:
          filters:
            branches:
              only:
                - main

# Just for reusing below
step_defs:
  - run: &node_version
      name: Set Node version
      command: |
        nvm install v16
        nvm alias default v16
        echo "nvm use default" >> $BASH_ENV
  - run: &check_version
      name: Check Node version
      command: node -v | grep v16

jobs:
  deploy:
    machine:
      image: ubuntu-2204:2022.04.1
    resource_class: large
    steps:
      - checkout
      - run: *node_version
      - run: *check_version
      - run:
          name: Install
          command: yarn
      - run:
          name: Load beta packages
          command: yarn loadBeta
      - run:
          name: Build backend image
          command: docker build . -t jchancehud/unirep-explorer:latest
      - run:
          name: Push backend image
          command: docker push jchancehud/unirep-explorer:latest
      - run:
          name: Build frontend
          command: cd packages/frontend && yarn build --mode production
      - run:
          name: Publish frontend
          command: wrangler publish

  lint:
    machine:
      image: ubuntu-2204:2022.04.1
    resource_class: medium
    steps:
      - checkout
      - run: *node_version
      - run: *check_version
      - run:
          name: Install
          command: yarn
      - run:
          name: Lint
          command: yarn lint --check
